[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[start]
cmd = "cd ./backend && python3 -m venv .venv && source .venv/bin/activate && pip install --no-cache-dir --break-system-packages -r requirements.txt && python3 -m uvicorn main:app --host 0.0.0.0 --port 8000"

[project]
language = "python"
